apiVersion: v1
kind: Service
metadata:
  name: {{ include "joegcservices.fullname" . }}-postgres
  labels:
    {{- include "joegcservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    {{- include "joegcservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
