apiVersion: v1
kind: Service
metadata:
  name: {{ include "joegcservices.fullname" . }}-data-pipeline-ingester
  labels:
    {{- include "joegcservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-pipeline
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: http-ing
      name: http
  selector:
    {{- include "joegcservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: data-pipeline
