apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weather-wms.fullname" . }}-models
  labels:
    {{- include "weather-wms.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $path, $_ := .Files.Glob "config/models/**.yaml" }}
  {{ base $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
